#server:
#  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: '{cipher}AgCBXlhDbey3gFtShlDHCAvZQSffWA/XV1fCRTAkrz+fFeTCeDi6GbCz4EWrp22L1NfaVcz5CiFBy1Z1LkjaW0H9Kw+MK/s8jniQiTQBZLJMQJK4hCut8XtZAhZnWRjwKB78AWUVHFN0Iwzi2AdAhlQnFwtQKVEAB6BlY01CYlr/D1vdcSnfLZnXfyoMqJflS2g+eOkd1YoKB5lTVBBEHMCpPiwP5a53sli8T6VM9LGGoTS2PUXoPR0r8+ZAKen4mLM/9V7Z0X2RwJZIJb1fe/z7SzEQUD/kV14cHJ/xWqKlrS4MxVr4/2CxFpKJ5x2UC2st/0hP8FP/2F6wJq4wKnZsjaKQa9x/iu3NydYDQZo1UvPl045BoBaY2Bu4LUV1n5PvLOISa9A/2c7miin4gCSD8yoAuqslL03DZ+6ZyBjylpJGDpwOOYab7F1LARA7gQSGWnTnOiW7kZqf/yuTgYxDWbG8gm57wHu845/CwErEecm/Nl85woJ1aDPFjDYCXjhKXUn8ONfY2EpDVLmNNavWgKdp6HfGodJOkZdZHKzWuru74Mdhjub667xV98ZOHvcY9+A9kOd1hOho8nTzwCSr8WVspqeg0uTG6u4vok5AE1fvnAOkLqh03ml+LikuSB2Yao67iZ8SOfFY0l2jZUtIAyueZCWENRk/IZGa7d7Ez/PHw0fDU5wtOzfOIgquXjsx/SI8BnbaHj1MpS/DJ5oT'
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  build:
    version:"1.0"
 
  
accounts:
    message: "welcome to RD bank default......."
    contactDetails:
           name: "John Doe - Developer"
           email: "john@eazybank.com"
    OnCallSupport:
      - 00566834934
      - 00645434344
      
