#server:
#  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#  h2:
#    console:
#      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
    show-sql: true
  build:
    version:"1.0"
 
  
accounts:
    message: "welcome to RD bank default.......****"
    contactDetails:
           name: "John Doe - Developer"
           email: "john@eazybank.com"
    OnCallSupport:
      - 00566834934
      - 00645434344
      
