#server:
#  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: "{cipher}AgCJecZYBFNLQEvCkNPFM7UgKvqaVC0O7dJfwIIs86amD+fD88MkuoujwnO2IvZZ60X3UGaEujqLbDNrnyMTa3f+c7HaF1IL204x2tponTvJhIE5WforCRvLx1mhuqGR1apEm6sYqPTPKcqBzO2+RERhJAxoAshIcCpYc616/oMD76HfOpbbWGKWyC7fytIJ4fwdoWL090AHPwJB98a4pJOJZ5Hm5nduKp5dSz/sPRlp51+FtRZKmpqvVxGoBJV/NgAPajxMLXX5gERGb+SKnDNddQzrthA8+7NDFODmSaKioPgijHKcbOxIZEs2eHHvTesQ6LdSqFLuZJF4sgJeckzVWW83hhTa+y5wxGeBYf4cZ9KtP3majwIf7PSZxz1fgKx+aoOTWyAiu3v6ps1nvmJRyT9MVg2MPhhkyxlGdohfUtQeRYlcN3wwTV2NBl5SHjOjg7Gmd+dGv90GLTTFdXM1v6ZWYxzkcKNcdPFa3evQTCqAFD4Y6ouR8a/fiJ9trZNrtpI1aT4HuAn29QR8r3joP56Tqr/qFe+yESNjIeDf1x0QFzsLmTIvbztA+5xEH5LI8fZv+zbzDqURdfq3hiO3LPw6DlyW3S9xaFp+7GwBkczbsovBH9BbXRyMiz2gRVguyuQ8LD9DVSb5BfFdUS+ZmzUc32TtwEd7SoMU8mupVNLGgYdxcmD+8bNgwBl3CMtt4TuPqzZIwAQaszwu4/hG"
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  build:
    version:"1.0"
 
  
accounts:
    message: "welcome to RD bank"
    contactDetails:
           name: "John Doe - Developer"
           email: "john@eazybank.com"
    OnCallSupport:
      - 00566834934
      - 00645434344
      
