#server:
 # port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#  h2:
#    console:
#      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
    show-sql: true
loans:
  message: welcome to dockern docker docker default loans microservices
  contactDetails: 
      name: jerry
      email: jerry@gmail.com
  onCallSupport:
      - 949349023493
      - 454354454455
